#spring.data.mongodb.uri=mongodb://localhost:27017/cloudshare


#spring.data.mongodb.uri=mongodb+srv://radhikabacharwar20_db_user:HQEWxvnC8LahRcFC@cluster0.cfmenli.mongodb.net/?appName=Cluster0
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/cloudshare}


server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration


#clerk.issuer=https://credible-porpoise-86.clerk.accounts.dev
#clerk.jwks-url=https://credible-porpoise-86.clerk.accounts.dev/.well-known/jwks.json
#clerk.webhook.secret=9qUhRYfu5K+MWgY26LRiqdkvpaglur4Z


spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/cloudshare}

server.servlet.context-path=/api/v1.0
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=${CLERK_ISSUER:https://credible-porpoise-86.clerk.accounts.dev}
clerk.jwks-url=${CLERK_JWKS_URL:https://credible-porpoise-86.clerk.accounts.dev/.well-known/jwks.json}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET:9qUhRYfu5K+MWgY26LRiqdkvpaglur4Z}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_SnD2uBhZcyZIol}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:clT0AUM9roM12NqnRPzX3Zbz}

#razorpay configuration
razorpay.key.id=rzp_test_SnD2uBhZcyZIol
razorpay.key.secret=clT0AUM9roM12NqnRPzX3Zbz